# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      Deployment template for the Platform Serices
      project registry.
    iconClass: icon-node
  name: platform-services-registry
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: platsrv-registry
    name: ${POSTGRESQL_SECRET_NAME}
  stringData:
    password: ${POSTGRESQL_PASSWORD}
    user: app_api_${POSTGRESQL_USER}
  type: Opaque
parameters:
- description: The secret name of database.
  displayName: PostgreSQL secret name
  name: POSTGRESQL_SECRET_NAME
  value: registry-postgres-creds
- displayName: The PostgreSQL db user name
  from: '[a-z0-9]{8}'
  generate: expression
  name: POSTGRESQL_USER
  required: true
- displayName: The PostgreSQL user password
  from: '[a-z0-9]{16}'
  generate: expression
  name: POSTGRESQL_PASSWORD
  required: true
